select count(distinct customer_id) from "Shopping_data";
SELECT * from shopping;
ALTER TABLE "Shopping_data" RENAME TO shopping;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) as revenue from shopping group by gender;
--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount from shopping where purchase_amount > (select avg(purchase_amount) from shopping) and discount_applied='Yes';
-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,ROUND(avg(review_rating)::NUMERIC,2) average from shopping group by item_purchased order by average desc limit 5;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,ROUND(avg(purchase_amount)::NUMERIC,2) average from shopping where shipping_type in ('Standard','Express') group by shipping_type;
--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,count(customer_id),ROUND(AVG(purchase_amount)::NUMERIC,2) average,
ROUND(SUM(purchase_amount)::NUMERIC,2) summation from shopping group by subscription_status;
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,ROUND((count(*) FILTER(where discount_applied='Yes')*100.0/count(*)),2) as percentage_of_purchases
from shopping group by item_purchased order by percentage_of_purchases desc LIMIT 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cte as
(
select customer_id,previous_purchases,
CASE 
	WHEN previous_purchases <2 then 'New'
	WHEN previous_purchases between 2 and 10 then 'Returning'
	ELSE 'Loyal'
END as segment 
from shopping
)
select segment,count(customer_id) as cnt from cte group by segment;


--Q8. What are the top 3 most purchased products within each category?
with cte as 
(
select category,item_purchased,count(item_purchased) as cnt,
DENSE_RANK() over(partition by category order by count(item_purchased) desc) as ran 
from shopping group by category,item_purchased
)
select category,item_purchased,cnt from cte where ran<4;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) from shopping where previous_purchases > 5 group by subscription_status;
--Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) revenue_contribution from shopping group by age_group order by revenue_contribution desc;


